### ISSUE TITLE
An error occurred while using admin commands

### ISSUE THREAD

**Issue by sky1683589933** [beyond-aion/aion-server#4]
### Description

An error occurred while using the 9th level administrator to execute the "//reload npcs" command. Compile using JDK21.0.3, but the server files remain unchanged.
[server_errors.log](https://github.com/user-attachments/files/15875554/server_errors.log)

### Reproduction steps

1.
2.
3.

**Comment by neon-dev** [comment]
Fixing this requires loading item templates within the same JAXBContext, due to `@XmlIDREF` annotated `ItemTemplate` references inside the npc templates.
We are not going to put work into this but would rather remove the option to reload npc templates.
A server restart is quick enough for this and reloading npc templates also doesn't really make a lot of sense, because it only affects new spawns and pollutes the heap a lot.
